version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  app:
    build: .
    container_name: prague_events_chat_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_storage:
